services:
  backend-test:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    container_name: shortvideo-backend-test
    environment:
      SPRING_PROFILES_ACTIVE: test

  frontend-test:
    build:
      context: ./frontend
      dockerfile: Dockerfile.test
    container_name: shortvideo-frontend-test
